# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-20 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=60)),
                ('this_quote', models.TextField(max_length=1000)),
                ('liked_users', models.ManyToManyField(related_name='liked_books', to='login_app.User')),
                ('quoter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quoted', to='login_app.User')),
            ],
        ),
    ]
