# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-12 21:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors', '0002_author_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='book_id',
            new_name='books',
        ),
    ]
